version: "3.9"
services:
  nginx:
    image: nginx:alpine
    container_name: lab2_nginx
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - ./www:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:8.2-fpm
    container_name: lab2_php
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"